---
jenkins_plugins:
  - ansicolor
  - any-buildstep
  - envinject
  - flexible-publish
  - ghprb
  - git
  - job-dsl
  - jenkins-multijob-plugin
  - nodelabelparameter
  - parameterized-trigger
  - swarm
  - throttle-concurrents
