---
- name: Check for DCenter command
  stat:
    path: "/opt/dcenter/bin/dc"
  register: dc

- name: Fail if DCenter command does not exit
  fail:
    msg: "The dc command does not exist at '/opt/dcenter/bin/dc'."
  when: not (dc.stat.isreg is defined and dc.stat.isreg)

- name: Unregister DCenter instance
  shell: "{{ dc.stat.path }} unregister --expires 2 {{ instance_name }}"
  when: (instance_name is defined and instance_name != "") and
    (unregister_only is defined and unregister_only == 'yes')

- name: Destroy DCenter instance
  shell: "{{ dc.stat.path }} destroy {{ instance_name }}"
  when: (instance_name is defined and instance_name != "") and
    not (unregister_only is defined and unregister_only == 'yes')
